# https://cloud.google.com/appengine/docs/python/modules/
application: twitter-gnip
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: app.application
  
libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest
  
skip_files:
- ^data$
